# Generated by Django 5.2.3 on 2025-06-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_program_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
