# Generated by Django 5.2.3 on 2025-06-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_programimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccordBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='businesses/')),
                ('sector', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
