# Generated by Django 5.0.2 on 2025-07-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
