# Generated by Django 5.0.2 on 2025-07-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_companyinfo_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccordGroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField()),
                ('strategic_vision', models.TextField()),
            ],
        ),
    ]
